services:
  # Base de donnÃ©es PostgreSQL
  db:
    restart: always
    container_name: shopeasy_db
    image: postgres:14.19-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SHOPEASY
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SHOPEASY"]
      interval: 10s
      timeout: 5s
      retries: 5
  # Backend Django
  backend:
    container_name: shopeasy_backend
    build: ./backend
    volumes:
      - ./backend/:/backend
    working_dir: /backend
    environment:
      - DATABASE_NAME=SHOPEASY
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=supersecretpassword
      - MINIO_DEFAULT_BUCKETS=produit-media-bucket
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_healthy
    ports:
      - 8000:8000
  # Frontend React
  frontend:
    container_name: shopeasy_frontend
    volumes:
      - ./frontend:/home/node
      - /home/node/node_modules
    build: ./frontend
    working_dir: /home/node
  # Nginx reverse proxy
  nginx:
    container_name: shopeasy_nginx
    build: ./nginx
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    ports:
      - 5173:8080
  # Redis pour cache et sessions
  redis:
    container_name: shopeasy_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  mailhog:
    image: mailhog/mailhog:latest
    container_name: shopeasy_mailhog
    ports:
      - "1025:1025"
  minio:
    image: minio/minio:latest
    container_name: shopeasy_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=supersecretpassword
      - MINIO_DEFAULT_BUCKETS=produit-media-bucket
    volumes:
      - minio_data:/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server /data --console-address :9001
  minio-init:
    image: minio/mc:latest
    container_name: shopeasy_minio_init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=supersecretpassword
      - MINIO_DEFAULT_BUCKETS=produit-media-bucket
    entrypoint: >
      /bin/sh -c "
      mc alias set storage http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      mc mb storage/$${MINIO_DEFAULT_BUCKETS} --ignore-existing;
      mc anonymous set download storage/$${MINIO_DEFAULT_BUCKETS};
      exit 0;
      "

volumes:
  postgres_data:
  redis_data:
  minio_data: