name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build les containers
        run: |
          docker compose -f docker-compose.ci.yml up --build -d
          sleep 30

      - name: Enregistrer une image
        run: |
          docker commit shopeasy_db shopeasy_db:latest
          docker commit shopeasy_backend shopeasy_backend:latest
          docker commit shopeasy_frontend shopeasy_frontend:latest
          docker commit shopeasy_nginx shopeasy_nginx:latest
          docker commit shopeasy_redis shopeasy_redis:latest
          docker commit shopeasy_mailhog shopeasy_mailhog:latest
          docker commit shopeasy_minio shopeasy_minio:latest
          docker save shopeasy_db:latest shopeasy_backend:latest shopeasy_frontend:latest shopeasy_nginx:latest shopeasy_redis:latest shopeasy_mailhog:latest shopeasy_minio:latest-o shopeasy.tar

      - name: Uploader une image en tant qu'artifact
        uses: actions/upload-artifact@v4
        with:
          name: shopeasy-image
          path: shopeasy.tar
  test:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Télécharger l'artifact
        uses: actions/download-artifact@v4
        with:
          name: shopeasy-image
          path: .

      # Téléchargement de l'image à corriger
      - name: Télécharger l'image
        run: |
          docker load -i shopeasy.tar
          docker image ls -a
          docker compose -f docker-compose.ci.yml up --build -d
          sleep 30

      - name: Exécuter test API
        run: |
          docker exec shopeasy_backend python manage.py test tests

  quality_gate:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: (Backend) Analyse du code
        uses: dciborow/action-pylint@0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          workdir: backend
          pylint_args: "--rcfile=.pylintrc"

      - name: (Backend) Vérification du formatage
        uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          workdir: backend
          black_args: "--check ."
          level: warning
      
      - name: Install dependencies
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "20"

      - run: |
          cd frontend
          npm install eslint eslint-plugin-react-hooks eslint-plugin-react-refresh -D
      
      - name: (Frontend) Analyse du code
        uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd # v1.33.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: frontend
          reporter: github-pr-review
          level: warning
